"""Per-country Laplacian spectra and k choice -> results/spectrum.csv, reports/spectrum.md.

    python -m src.cluster.kselect
"""

from __future__ import annotations

import json

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src import config
from src.cluster import spectrum as S
from src.cluster.graphs import country_nodes

RESULTS = config.ROOT / "results"
INTERIM = config.ROOT / "data" / "interim"
FIGS = config.ROOT / "figures"
REPORTS = config.ROOT / "reports"


def run(cfg=None):
    cfg = cfg or config.load()
    edges = pd.read_parquet(RESULTS / "edges.parquet")
    buses = pd.read_csv(INTERIM / "buses.csv", index_col=0)
    sc = cfg["spectrum"]
    rows, spectra = [], {}
    for c in sorted(edges.country.unique()):
        nodes, _ = country_nodes(c, buses, edges)
        e = edges[edges.country == c]
        e = e[e.bus_a.isin(nodes) & e.bus_b.isin(nodes)]
        ev = S.laplacian_spectrum(nodes, e)
        ch = S.choose_k(ev, sc["k_max"], sc["gap_ratio"], sc["k_fallback"], len(nodes))
        spectra[c] = ev.tolist()
        rows.append({"country": c, "n_nodes": len(nodes), **ch})
    df = pd.DataFrame(rows).set_index("country")
    df.to_csv(RESULTS / "spectrum.csv")
    (RESULTS / "spectra.json").write_text(json.dumps(spectra))
    plot(spectra, df, sc)
    report(df, sc)
    return df


def plot(spectra, df, sc):
    cs = sorted(spectra)
    ncol = 6
    nrow = int(np.ceil(len(cs) / ncol))
    for kind in ("full", "zoom"):
        fig, axes = plt.subplots(nrow, ncol, figsize=(2.6 * ncol, 2.1 * nrow), squeeze=False)
        for ax, c in zip(axes.ravel(), cs):
            ev = np.array(spectra[c])
            r = df.loc[c]
            if kind == "full":
                ax.plot(np.arange(1, len(ev) + 1), ev, ".", ms=2, color="0.3")
            else:
                m = min(len(ev), sc["k_max"] + 4)
                ax.plot(np.arange(1, m + 1), ev[:m], "o-", ms=3, lw=0.8, color="0.3")
            if r.k_elbow is not None and not pd.isna(r.k_elbow):
                k = int(r.k_elbow)
                ax.axvline(k + 0.5, color="C3" if r.convincing else "C1", lw=1,
                           ls="-" if r.convincing else "--")
            ax.set_title(f"{c} n={int(r.n_nodes)} k*={r.k_elbow} s={r.significance:.1f} "
                         f"{'✓' if r.convincing else '✗'}", fontsize=7)
            ax.tick_params(labelsize=6)
        for ax in axes.ravel()[len(cs):]:
            ax.axis("off")
        fig.suptitle(f"Normalised-Laplacian spectra ({kind}); line = most significant eigengap, "
                     f"2≤k≤{sc['k_max']} (solid red: ≥{sc['gap_ratio']}× local spacing; dashed orange: not)",
                     fontsize=9)
        fig.tight_layout()
        fig.savefig(FIGS / f"spectra_{kind}.png", dpi=150)
        plt.close(fig)


def report(df, sc):
    conv = df[df.convincing]
    lines = [
        "# Laplacian spectra and the choice of k",
        "",
        "Generated by `python -m src.cluster.kselect`. Graph: intra-country edges weighted by the",
        "normalised (post-remedy) susceptance J̃; HVDC edges weighted at the country's median J̃;",
        "normalised Laplacian `I − D^-1/2 W D^-1/2`. Elbow: for 2 ≤ k ≤ "
        f"{sc['k_max']}, the gap λ_(k+1) − λ_k divided by the median of its neighbouring gaps",
        "(±3 indices). The plain largest gap is biased to k_max on near-planar graphs, whose",
        "spacing grows with index, so it is reported (`k_largest_gap`) but not used. *Convincing*",
        f"if the local significance is ≥ {sc['gap_ratio']}; otherwise the documented fallback",
        f"k = {sc['k_fallback']} is used. The search is capped at k ≤ max(2, n/4) (at least ~4",
        "buses per zone): on small graphs a 'gap' near k ≈ n is not a zoning signal.",
        "",
        f"**{len(conv)} of {len(df)} countries have a convincing elbow.** Where it is not",
        "convincing the k used is a default, not a finding. Expect weak signals: transmission graphs",
        "are near-planar meshes without natural community structure in susceptance alone.",
        "",
        "![full](../figures/spectra_full.png)",
        "",
        "![zoom](../figures/spectra_zoom.png)",
        "",
        df.round(4).to_markdown(),
    ]
    (REPORTS / "spectrum.md").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    pd.set_option("display.width", 250)
    print(run().round(4).to_string())
