"""Markdown reports for the data and solve phases.

    python -m bzgen.report data     # after bzgen.network.assemble -> reports/data.md
    python -m bzgen.report solve    # after bzgen.solve.run        -> reports/solve.md
"""

from __future__ import annotations

import json
import sys

import numpy as np
import pandas as pd

from bzgen import config

ROOT = config.ROOT
REPORTS = ROOT / "reports"
INTERIM = ROOT / "data" / "interim"
SOLVED = ROOT / "data" / "solved"

# Typical published annual capacity factors, for an order-of-magnitude sanity
# check of the ERA5 conversion only (NOT a calibration target).  INFERENCE:
# author's recollection of commonly cited ranges, not a sourced dataset.
TYPICAL = {"onwind": (0.18, 0.35), "offwind": (0.35, 0.50), "solar": (0.09, 0.20)}


def md(df: pd.DataFrame, digits=2) -> str:
    return df.round(digits).to_markdown()


def data_report(out: dict, cfg: dict) -> str:
    r = out["reports"]
    topo = pd.DataFrame(r["topology"])
    dem = r["demand"]
    key = r["load_key"]
    res = r["res_targets"]
    hyd = r["hydro_cf"]
    gens = out["gens"]
    prof = out["prof"]
    buses = out["buses"]
    flags = []
    for c, row in dem.iterrows():
        if row.get("status") != "ok":
            flags.append(f"- **{c}** demand: {row.get('status')} — shape `{row.get('shape_source')}`, "
                         f"level `{row.get('scale_method')}`")
    for c, row in key.iterrows():
        if "FLAG" in str(row.method):
            flags.append(f"- **{c}** load distribution: {row.method}")
    for _, row in res.iterrows():
        if "FLAG" in str(row.action):
            flags.append(f"- **{row.country} {row.carrier}**: {row.action}")
    for c, row in r["wind_calibration"].iterrows() if len(r["wind_calibration"]) else []:
        if "FLAG" in str(row.get("note", "")):
            flags.append(f"- **{c}** onshore wind calibration: {row.note} (obs CF "
                         f"{row.obs_cf:.3f}, calibrated {row.model_cf_cal:.3f})")
    for c, row in hyd.iterrows():
        if "DEFAULT" in str(row.source) and c in set(buses.country):
            flags.append(f"- **{c}** hydro CF: {row.source} ({row.cf:.2f})")
    absent = sorted(set(cfg["scope"]["countries"]) - set(buses.country))
    # CF sanity check
    cf_rows = []
    for c in sorted(buses.country.unique()):
        for car in ("onwind", "offwind", "solar"):
            g = gens[(gens.country == c) & (gens.carrier == car) & gens.index.isin(prof.columns)]
            if g.p_nom.sum() < 1:
                continue
            cf = float((prof[g.index] * g.p_nom).sum(1).mean() / g.p_nom.sum())
            lo, hi = TYPICAL[car]
            cf_rows.append({"country": c, "carrier": car, "GW": g.p_nom.sum() / 1e3, "annual_cf": cf,
                            "check": "" if lo <= cf <= hi else f"OUTSIDE typical {lo:.2f}-{hi:.2f}"})
    cf = pd.DataFrame(cf_rows).set_index(["country", "carrier"])
    cap = gens.pivot_table(index="country", columns="carrier", values="p_nom", aggfunc="sum").div(1e3)
    lines = [
        "# Data assembly report",
        "",
        "Generated by `python -m bzgen.report data`. Provenance of every input: "
        "[`data/PROVENANCE.md`](../data/PROVENANCE.md).",
        "",
        "## Loud flags",
        "",
        "Everything below is a fallback or a gap, not a measurement.",
        "",
        *flags,
        f"- **Countries in scope with no topology in the PyPSA-Eur OSM network (skipped): {absent}**",
        "- **Northern Ireland** is coded GB in the source and is dropped with GB (PLAN.md §1).",
        "- **GB, UA and MD interconnections** are dropped with those countries.",
        "- **Storage** (pumped hydro, batteries, H2, heat) is excluded as the brief requires: "
        f"{r['fleet']['excluded_storage_mw'] / 1e3:.1f} GW of powerplantmatching capacity.",
        "- **Reservoir hydro** is dispatchable up to 90 % at a water value with **no energy limit** "
        "(no storage), so its annual output is not constrained: see `reports/solve.md`.",
        "- **Marginal costs** are the author's 2025 estimates (config `costs`), not sourced data.",
        "",
        "## Topology (PyPSA-Eur OSM v0.7, Zenodo 18619025, md5-verified)",
        "",
        topo.to_markdown(index=False),
        "",
        "Microstates / small countries merged for partitioning (largest cross-border susceptance):",
        "",
        pd.DataFrame(r["merge"]).to_markdown(index=False),
        "",
        f"Surviving buses by country: {buses.country.value_counts().to_dict()}",
        "",
        "## Demand (OPSD 2019 shape, Eurostat AFC level)",
        "",
        md(dem),
        "",
        "## Load distribution key",
        "",
        f"Method: `{cfg['demand'].get('distribution', 'point_in_polygon')}`, weights GDP "
        f"{cfg['demand']['w_gdp']} / population {cfg['demand']['w_pop']} (PyPSA-Eur default).",
        "",
        md(key),
        "",
        "## Generation fleet",
        "",
        f"powerplantmatching tag {r['fleet']['ppm_tag']}: {r['fleet']}",
        "",
        "Installed capacity after scaling (GW):",
        "",
        md(cap, 1),
        "",
        "Wind/solar reconciliation with Eurostat `nrg_inf_epcrw` (latest year):",
        "",
        res.round(0).to_markdown(index=False),
        "",
        "Hydro capacity factors (weather year):",
        "",
        md(hyd),
        "",
        "## Weather-derived capacity factors (ERA5 via Open-Meteo, 2019)",
        "",
        "Onshore wind calibration (`calibrate_onwind`): one wind-speed scale per country so that",
        "the modelled 2019 wind CF matches Eurostat's observed 2019 CF (see",
        "`bzgen/network/assemble.py::calibrate_onwind`). Countries at a clip bound are flagged.",
        "",
        md(r["wind_calibration"], 3) if len(r["wind_calibration"]) else "_calibration disabled_",
        "",
        f"{len(out['pts'])} sample points (hex grid, {cfg['weather']['spacing_km']} km). "
        "Annual mean CF per country and carrier, against rough typical ranges (sanity check only).",
        "",
        md(cf, 3),
    ]
    return "\n".join(lines) + "\n"


def solve_report(cfg: dict) -> str:
    meta = json.loads((SOLVED / "meta.json").read_text())
    buses = pd.read_csv(INTERIM / "buses.csv", index_col=0)
    gens = pd.read_csv(INTERIM / "generators.csv", index_col=0)
    prices = pd.read_parquet(SOLVED / "prices.parquet")
    w = pd.read_csv(SOLVED / "snapshots.csv", index_col=0, parse_dates=True).weight
    shed = pd.read_parquet(SOLVED / "shed.parquet")
    cc = pd.read_parquet(SOLVED / "carrier_country.parquet")
    ww = w.reindex(cc.index).to_numpy()
    twh = pd.Series((cc.to_numpy() * ww[:, None]).sum(0) / 1e6, index=cc.columns)
    twh.index = pd.MultiIndex.from_tuples([tuple(i.split("|")) for i in twh.index],
                                          names=["country", "carrier"])
    gen_tab = twh.unstack("carrier").fillna(0.0)
    s = shed[shed.mw > cfg["solve"].get("shed_tol_mw", 1.0)]
    s = s.assign(country=s.bus.map(buses.country))
    by_c = s.groupby("country").agg(hours=("snapshot", "nunique"), GWh=("mw", lambda x: x.sum() / 1e3),
                                    buses=("bus", "nunique"))
    chronic = s.groupby("bus").agg(hours=("snapshot", "nunique"), GWh=("mw", lambda x: x.sum() / 1e3))
    chronic = chronic[chronic.hours >= 0.5 * len(prices)].sort_values("hours", ascending=False)
    chronic["country"] = chronic.index.map(buses.country)
    chronic["lon"] = chronic.index.map(buses.x).round(2)
    chronic["lat"] = chronic.index.map(buses.y).round(2)
    P = prices.to_numpy()
    wmean = pd.Series((w.reindex(prices.index).to_numpy()[:, None] * P).sum(0) / w.sum(),
                      index=prices.columns)
    pstat = pd.DataFrame({"mean_of_bus_means": wmean.groupby(buses.country).mean(),
                          "min_bus_mean": wmean.groupby(buses.country).min(),
                          "max_bus_mean": wmean.groupby(buses.country).max()})
    # reservoir energy vs Eurostat hydro generation
    hyd = pd.read_csv(INTERIM / "plants.csv")
    res_twh = gen_tab.get("reservoir", pd.Series(dtype=float)) + gen_tab.get("ror", pd.Series(dtype=float))
    lines = [
        "# Nodal-price solve report",
        "",
        "Generated by `python -m bzgen.report solve`. DC-OPF per hour (`bzgen/solve/lp.py`, checked",
        "against `pypsa.Network.optimize()`: identical objective and prices to 1e-3 EUR/MWh on",
        "check hours).",
        "",
        f"- snapshots solved: **{meta['n_snapshots']}**, not optimal: **{meta['not_optimal']}** "
        f"{meta.get('not_optimal_snapshots', [])}",
        f"- hours that needed a solver retry (cold restart / interior point): {meta.get('retries', [])}",
        f"- median solve time per hour: {meta['solve_seconds_median']:.3f} s",
        "",
        "## Load shedding",
        "",
        f"Shedding (> {cfg['solve'].get('shed_tol_mw', 1.0)} MW) occurs in "
        f"**{s.snapshot.nunique()} of {len(prices)} hours** "
        f"({s.snapshot.nunique() / len(prices):.1%}), {s.mw.sum() / 1e6:.2f} TWh in total, at "
        f"{s.bus.nunique()} buses.",
        "",
        md(by_c, 1),
        "",
        "**Chronic pockets** (shedding in ≥ 50 % of hours): buses whose 220 kV+ connection",
        "cannot carry their allocated load even at low demand. These are artefacts of truncating",
        "the grid at 220 kV (the 110 kV networks that also feed cities are absent) combined with",
        "GDP-weighted, point-in-polygon load allocation (a small, rich NUTS3 region such as a city",
        "puts its whole load on the one bus inside it). A Voronoi-overlap allocation (PyPSA-Eur's",
        "`redistribute_attribute`) was tested and **did not remove them** (it moved them).",
        "",
        md(chronic, 1),
        "",
        f"**Decision:** shedding occurs in almost every hour, so excluding shedding snapshots would",
        f"discard almost the whole year. Policy `{cfg['solve']['shedding_policy']}`: prices are clipped",
        f"to ±{cfg['solve']['price_clip']:.0f} EUR/MWh before any statistic (above the most expensive",
        "real generator, below the shedding cost). With the default *duration* statistic (share of",
        "hours with |Δp| > threshold) clipping only affects hours where both ends exceed the cap.",
        "",
        "## Prices",
        "",
        f"Raw price range {np.nanmin(P):.0f} .. {np.nanmax(P):.0f} EUR/MWh; share of bus-hours above "
        f"+{cfg['solve']['price_clip']:.0f}: {(P > cfg['solve']['price_clip']).mean():.4f}, below "
        f"−{cfg['solve']['price_clip']:.0f}: {(P < -cfg['solve']['price_clip']).mean():.4f}. "
        "Prices beyond the most expensive generator and negative prices are genuine DC-OPF",
        "outcomes under binding line limits (loop-flow effects), amplified around shedding pockets.",
        "",
        md(pstat, 1),
        "",
        "## Annual energy by carrier (TWh)",
        "",
        md(gen_tab, 1),
        "",
        "Hydro (reservoir + run-of-river) is unconstrained in energy (no storage modelled); compare",
        "with Eurostat natural-hydro generation in `reports/data.md` (hydro CF table).",
        "",
        "![prices](../figures/nodal_prices.png)",
    ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    cfg = config.load()
    what = sys.argv[1]
    REPORTS.mkdir(exist_ok=True)
    if what == "solve":
        (REPORTS / "solve.md").write_text(solve_report(cfg))
    elif what == "data":
        from bzgen.network.assemble import assemble
        out = assemble(cfg)
        (REPORTS / "data.md").write_text(data_report(out, cfg))
