"""Annealer validation on planted partitions -> reports/annealer_validation.md.

Run: python -m bzgen.cluster.validate
"""

from __future__ import annotations

import time

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import adjusted_rand_score as ari

from bzgen import config
from bzgen.cluster.anneal import anneal, energy_terms
from bzgen.cluster.synthetic import planted, to_graph

OUT = config.ROOT / "reports" / "annealer_validation.md"
FIG = config.ROOT / "figures" / "annealer_validation.png"


def run(seeds=range(8), ks=(3, 5, 8), restarts=8, lam_c0=0.1, lam_b=0.1, floor=0.02):
    cfg = config.load()["anneal"]
    rows, example = [], None
    for seed in seeds:
        for k in ks:
            p = planted(n=400, k=k, seed=seed)
            g = to_graph(p)
            ep, cs, pb = energy_terms(p["truth"], k, g.ptr, g.idx, g.w, g.Lnode, g.Gnode,
                                      g.Ltot, floor)
            t = time.time()
            res = [anneal(g, k, lam_b=lam_b, lam_c0=lam_c0, lam_c1="auto", floor=floor,
                          n_temps=cfg["n_temps"], sweeps_per_temp=cfg["sweeps_per_temp"],
                          t_final_ratio=cfg["t_final_ratio"], seed=s) for s in range(restarts)]
            wall = time.time() - t
            E = np.array([r["energy"] for r in res])
            best = res[int(E.argmin())]
            truth_E = ep + lam_b * pb + (best["lam_c_final"] * cs)
            rows.append({
                "seed": seed, "k": k, "n": g.n, "truth_contiguous": cs == 0,
                "ari_best": ari(p["truth"], best["labels"]),
                "ari_median_restart": float(np.median([ari(p["truth"], r["labels"]) for r in res])),
                "E_best": E.min(), "E_truth": truth_E, "E_best_minus_truth": E.min() - truth_E,
                "E_spread": float(np.ptp(E)),
                "frac_restarts_at_best": float(np.mean(E - E.min() < 1e-6)),
                "all_contiguous": all(r["contig"] == 0 for r in res),
                "wall_s": wall,
            })
            if example is None and cs == 0 and k == 5:
                example = (p, best["labels"])
    return pd.DataFrame(rows), example


def main():
    df, ex = run()
    ok = df[df.truth_contiguous]
    fig, ax = plt.subplots(1, 3, figsize=(13, 4.2))
    if ex is not None:
        p, lab = ex
        for a, l, t in ((ax[0], p["truth"], "planted"), (ax[1], lab, "annealed (best restart)")):
            e = p["edges"]
            a.plot(p["xy"][e.T, 0], p["xy"][e.T, 1], color="0.85", lw=0.4, zorder=0)
            a.scatter(p["xy"][:, 0], p["xy"][:, 1], c=l, cmap="tab10", s=10, zorder=1)
            a.set_title(t); a.set_aspect("equal"); a.set_xticks([]); a.set_yticks([])
    ax[2].scatter(df.k + np.random.default_rng(0).uniform(-0.15, 0.15, len(df)), df.ari_best,
                  c=np.where(df.truth_contiguous, "C0", "C3"), s=18)
    ax[2].set_xlabel("k"); ax[2].set_ylabel("ARI (best restart vs planted)")
    ax[2].set_title("recovery (red: planted partition not contiguous)")
    ax[2].set_ylim(0, 1.05)
    fig.tight_layout(); fig.savefig(FIG, dpi=160); plt.close(fig)
    lines = [
        "# Annealer validation on planted partitions",
        "",
        "Generated by `python -m bzgen.cluster.validate`. Benchmark: `bzgen/cluster/synthetic.py` —",
        "random geometric graph (n≈400) split into k Voronoi zones; price gap high on crossing",
        "edges (×15 vs inside, lognormal noise σ=0.3), susceptance lognormal (σ=0.8) and",
        "independent of the zones; both normalised to mean 1; α = 1; λ_b = 0.1, floor 2 %;",
        "λ_c ramps from 0.1 to the automatic contiguity guarantee; 8 restarts; schedule from",
        "`config/default.yaml`.",
        "",
        "Energies of the planted partition are evaluated at the same final λ_c. When the planted",
        "Voronoi partition is itself non-contiguous on the sampled graph (red in the figure) it is",
        "not a valid target under the contiguity constraint, so those cases are listed separately.",
        "",
        f"**Contiguous planted cases ({len(ok)}):** mean ARI {ok.ari_best.mean():.3f}, "
        f"min {ok.ari_best.min():.3f}; best restart reaches the planted energy or lower in "
        f"{int((ok.E_best_minus_truth <= 1e-6).sum())}/{len(ok)}; worst excess "
        f"{ok.E_best_minus_truth.max():.2f}; every restart contiguous in "
        f"{int(ok.all_contiguous.sum())}/{len(ok)}.",
        "",
        f"**All cases ({len(df)}):** mean ARI {df.ari_best.mean():.3f}; all restarts contiguous in "
        f"{int(df.all_contiguous.sum())}/{len(df)}.",
        "",
        "Design history (kept because it matters for trusting the real runs):",
        "",
        "1. Single-node flips alone froze at ≈T0/4 with disconnected fragments locked in; the best",
        "   of 6 restarts missed the planted energy in 5/6 cases and ended non-contiguous.",
        "2. Adding **fragment moves** (a whole non-largest component of a zone offered to its best",
        "   adjacent zone, Metropolis-accepted, once per temperature step) recovered the planted",
        "   partition in most cases.",
        "3. Some fragments cost more than a fixed λ_c,final = 5 or 50 to attach (boundary weight",
        "   60–340); these are k-frustrated states (one label spread over two planted regions).",
        "   λ_c,final is therefore set automatically above the bound on any Potts + balance change",
        "   (Σ|w| + 2λ_b + 1), which makes the T=0 fragment pass always restore contiguity.",
        "4. Starting the λ_c ramp high hurts (ARI 0.99 → 0.92 → 0.73 for λ_c0 = 0.1, 0.5, 2):",
        "   strong early contiguity pressure freezes the chain. Default λ_c0 = 0.1.",
        "",
        "![validation](../figures/annealer_validation.png)",
        "",
        df.round(3).to_markdown(index=False),
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print("\n".join(lines[:22]))


if __name__ == "__main__":
    main()
